// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/index.tsx";
import * as $1 from "./routes/notes/[id].tsx";
import * as $2 from "./routes/notes/index.tsx";
import * as $3 from "./routes/notes/new.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/DeleteButton.tsx";
import * as $$2 from "./islands/MDEdit.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
    "./routes/notes/[id].tsx": $1,
    "./routes/notes/index.tsx": $2,
    "./routes/notes/new.tsx": $3,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/DeleteButton.tsx": $$1,
    "./islands/MDEdit.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
